name: Mirror

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TZ: Asia/Shanghai

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Docker
        run: |
          docker version
          docker info

      - name: Test Mirrors
        run: |
          date_suffix=$(date +"%Y-%m-%d")
          output_file="logs/dockerhub-mirrors-${date_suffix}.md"
          image="library/busybox:latest"

          {
            echo "# DockerHub 镜像仓库测试结果 (${date_suffix})"
            echo ""
            echo "| DockerHub 镜像仓库 | 状态 | 下载时间 (秒) |"
            echo "| ------------------ | ---- | ------------- |"
          } > $output_file

          success_records=()
          fail_records=()

          while IFS= read -r mirror; do
            echo "正在测试 $mirror"
            start_time=$(date +%s%3N)

            if docker pull $mirror/$image; then
              status="✅ 正常"
            else
              status="❌ 失败"
            fi

            end_time=$(date +%s%3N)
            elapsed_time=$(echo "scale=3; ($end_time - $start_time)/1000" | bc)
            formatted_elapsed_time=$(printf "%.3f" $elapsed_time)

            record="$mirror | $status | $formatted_elapsed_time"
            if [ "$status" = "✅ 正常" ]; then
              success_records+=("$record")
            else
              fail_records+=("$record")
            fi

            docker rmi $mirror/$image || true
          done < docs/dockerhub-mirrors.txt

          IFS=$'\n' sorted_success=($(sort -t '|' -k 3 -n <<<"${success_records[*]}"))
          for record in "${sorted_success[@]}"; do
            echo "| $record |" >> $output_file
          done

          for record in "${fail_records[@]}"; do
            echo "| $record |" >> $output_file
          done

          find "logs" -name "dockerhub-mirrors-*.md" -type f -mtime +30 -exec rm {} \;

          cp -af "$output_file" "README.md"

          echo "TIME=$(date +"%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV

      - name: Upload to repository
        uses: stefanzweifel/git-auto-commit-action@master
        with:
          commit_message: ${{ env.TIME }}
