name: Mirror

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TZ: Asia/Shanghai

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Docker
        run: |
          docker version
          docker info

      - name: Test Mirrors
        run: |
          find logs -name "dockerhub-mirrors-*.md" -type f -mtime +30 -exec rm {} \;

          echo "TIME=$(date +"%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV
